<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OrdersHistory', 'doctrine');

/**
 * BaseOrdersHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $idorders
 * @property integer $fkidorder_status
 * @property integer $fkidorder_type
 * @property integer $fkidbasket
 * @property timestamp $created_at
 * 
 * @method integer       getId()               Returns the current record's "id" value
 * @method integer       getIdorders()         Returns the current record's "idorders" value
 * @method integer       getFkidorderStatus()  Returns the current record's "fkidorder_status" value
 * @method integer       getFkidorderType()    Returns the current record's "fkidorder_type" value
 * @method integer       getFkidbasket()       Returns the current record's "fkidbasket" value
 * @method timestamp     getCreatedAt()        Returns the current record's "created_at" value
 * @method OrdersHistory setId()               Sets the current record's "id" value
 * @method OrdersHistory setIdorders()         Sets the current record's "idorders" value
 * @method OrdersHistory setFkidorderStatus()  Sets the current record's "fkidorder_status" value
 * @method OrdersHistory setFkidorderType()    Sets the current record's "fkidorder_type" value
 * @method OrdersHistory setFkidbasket()       Sets the current record's "fkidbasket" value
 * @method OrdersHistory setCreatedAt()        Sets the current record's "created_at" value
 * 
 * @package    artworks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrdersHistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orders_history');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('idorders', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fkidorder_status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fkidorder_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fkidbasket', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}