<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BasketStatus', 'doctrine');

/**
 * BaseBasketStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idbasket_status
 * @property string $label
 * @property Doctrine_Collection $Basket
 * 
 * @method integer             getIdbasketStatus()  Returns the current record's "idbasket_status" value
 * @method string              getLabel()           Returns the current record's "label" value
 * @method Doctrine_Collection getBasket()          Returns the current record's "Basket" collection
 * @method BasketStatus        setIdbasketStatus()  Sets the current record's "idbasket_status" value
 * @method BasketStatus        setLabel()           Sets the current record's "label" value
 * @method BasketStatus        setBasket()          Sets the current record's "Basket" collection
 * 
 * @package    artworks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBasketStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('basket_status');
        $this->hasColumn('idbasket_status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('label', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Basket', array(
             'local' => 'idbasket_status',
             'foreign' => 'fkidbasket_status'));
    }
}