<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DeliveryPricing', 'doctrine');

/**
 * BaseDeliveryPricing
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $iddelivery_pricing
 * @property decimal $price
 * @property integer $fkidcurrencyfromdelivery
 * @property Currency $Currency
 * @property Doctrine_Collection $DeliveryAreas
 * @property Doctrine_Collection $DeliveryPricingHistory
 * 
 * @method integer             getIddeliveryPricing()        Returns the current record's "iddelivery_pricing" value
 * @method decimal             getPrice()                    Returns the current record's "price" value
 * @method integer             getFkidcurrencyfromdelivery() Returns the current record's "fkidcurrencyfromdelivery" value
 * @method Currency            getCurrency()                 Returns the current record's "Currency" value
 * @method Doctrine_Collection getDeliveryAreas()            Returns the current record's "DeliveryAreas" collection
 * @method Doctrine_Collection getDeliveryPricingHistory()   Returns the current record's "DeliveryPricingHistory" collection
 * @method DeliveryPricing     setIddeliveryPricing()        Sets the current record's "iddelivery_pricing" value
 * @method DeliveryPricing     setPrice()                    Sets the current record's "price" value
 * @method DeliveryPricing     setFkidcurrencyfromdelivery() Sets the current record's "fkidcurrencyfromdelivery" value
 * @method DeliveryPricing     setCurrency()                 Sets the current record's "Currency" value
 * @method DeliveryPricing     setDeliveryAreas()            Sets the current record's "DeliveryAreas" collection
 * @method DeliveryPricing     setDeliveryPricingHistory()   Sets the current record's "DeliveryPricingHistory" collection
 * 
 * @package    artworks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeliveryPricing extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('delivery_pricing');
        $this->hasColumn('iddelivery_pricing', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('price', 'decimal', 15, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             'scale' => '2',
             ));
        $this->hasColumn('fkidcurrencyfromdelivery', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Currency', array(
             'local' => 'fkidcurrencyfromdelivery',
             'foreign' => 'idcurrency'));

        $this->hasMany('DeliveryAreas', array(
             'local' => 'iddelivery_pricing',
             'foreign' => 'fkiddelivery_pricing'));

        $this->hasMany('DeliveryPricingHistory', array(
             'local' => 'iddelivery_pricing',
             'foreign' => 'fkiddelivery_pricingfromhistory'));
    }
}