<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DeliveryAreas', 'doctrine');

/**
 * BaseDeliveryAreas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $iddelivery_areas
 * @property integer $fkiddelivery_pricing
 * @property DeliveryPricing $DeliveryPricing
 * @property Doctrine_Collection $Country
 * 
 * @method integer             getIddeliveryAreas()      Returns the current record's "iddelivery_areas" value
 * @method integer             getFkiddeliveryPricing()  Returns the current record's "fkiddelivery_pricing" value
 * @method DeliveryPricing     getDeliveryPricing()      Returns the current record's "DeliveryPricing" value
 * @method Doctrine_Collection getCountry()              Returns the current record's "Country" collection
 * @method DeliveryAreas       setIddeliveryAreas()      Sets the current record's "iddelivery_areas" value
 * @method DeliveryAreas       setFkiddeliveryPricing()  Sets the current record's "fkiddelivery_pricing" value
 * @method DeliveryAreas       setDeliveryPricing()      Sets the current record's "DeliveryPricing" value
 * @method DeliveryAreas       setCountry()              Sets the current record's "Country" collection
 * 
 * @package    artworks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeliveryAreas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('delivery_areas');
        $this->hasColumn('iddelivery_areas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fkiddelivery_pricing', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DeliveryPricing', array(
             'local' => 'fkiddelivery_pricing',
             'foreign' => 'iddelivery_pricing'));

        $this->hasMany('Country', array(
             'local' => 'iddelivery_areas',
             'foreign' => 'fkiddelivery_areas'));
    }
}