<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Country', 'doctrine');

/**
 * BaseCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcountry
 * @property string $label
 * @property integer $fkiddelivery_areas
 * @property string $country_code
 * @property DeliveryAreas $DeliveryAreas
 * @property Doctrine_Collection $DialingCodes
 * @property Doctrine_Collection $Geolocation
 * 
 * @method integer             getIdcountry()          Returns the current record's "idcountry" value
 * @method string              getLabel()              Returns the current record's "label" value
 * @method integer             getFkiddeliveryAreas()  Returns the current record's "fkiddelivery_areas" value
 * @method string              getCountryCode()        Returns the current record's "country_code" value
 * @method DeliveryAreas       getDeliveryAreas()      Returns the current record's "DeliveryAreas" value
 * @method Doctrine_Collection getDialingCodes()       Returns the current record's "DialingCodes" collection
 * @method Doctrine_Collection getGeolocation()        Returns the current record's "Geolocation" collection
 * @method Country             setIdcountry()          Sets the current record's "idcountry" value
 * @method Country             setLabel()              Sets the current record's "label" value
 * @method Country             setFkiddeliveryAreas()  Sets the current record's "fkiddelivery_areas" value
 * @method Country             setCountryCode()        Sets the current record's "country_code" value
 * @method Country             setDeliveryAreas()      Sets the current record's "DeliveryAreas" value
 * @method Country             setDialingCodes()       Sets the current record's "DialingCodes" collection
 * @method Country             setGeolocation()        Sets the current record's "Geolocation" collection
 * 
 * @package    artworks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('country');
        $this->hasColumn('idcountry', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('label', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('fkiddelivery_areas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('country_code', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DeliveryAreas', array(
             'local' => 'fkiddelivery_areas',
             'foreign' => 'iddelivery_areas'));

        $this->hasMany('DialingCodes', array(
             'local' => 'idcountry',
             'foreign' => 'fkidcountryfromdialingcodes'));

        $this->hasMany('Geolocation', array(
             'local' => 'idcountry',
             'foreign' => 'fkidcountry'));
    }
}