<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ArtworkStyle', 'doctrine');

/**
 * BaseArtworkStyle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idartwork_style
 * @property string $label
 * @property Doctrine_Collection $Artworks
 * 
 * @method integer             getIdartworkStyle()  Returns the current record's "idartwork_style" value
 * @method string              getLabel()           Returns the current record's "label" value
 * @method Doctrine_Collection getArtworks()        Returns the current record's "Artworks" collection
 * @method ArtworkStyle        setIdartworkStyle()  Sets the current record's "idartwork_style" value
 * @method ArtworkStyle        setLabel()           Sets the current record's "label" value
 * @method ArtworkStyle        setArtworks()        Sets the current record's "Artworks" collection
 * 
 * @package    artworks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtworkStyle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artwork_style');
        $this->hasColumn('idartwork_style', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('label', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Artworks', array(
             'local' => 'idartwork_style',
             'foreign' => 'fkidartwork_style'));
    }
}