<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CustomerStatus', 'doctrine');

/**
 * BaseCustomerStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcustomer_status
 * @property string $label
 * @property Doctrine_Collection $Customers
 * 
 * @method integer             getIdcustomerStatus()  Returns the current record's "idcustomer_status" value
 * @method string              getLabel()             Returns the current record's "label" value
 * @method Doctrine_Collection getCustomers()         Returns the current record's "Customers" collection
 * @method CustomerStatus      setIdcustomerStatus()  Sets the current record's "idcustomer_status" value
 * @method CustomerStatus      setLabel()             Sets the current record's "label" value
 * @method CustomerStatus      setCustomers()         Sets the current record's "Customers" collection
 * 
 * @package    artworks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustomerStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('customer_status');
        $this->hasColumn('idcustomer_status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('label', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Customers', array(
             'local' => 'idcustomer_status',
             'foreign' => 'fkidcustomer_status'));
    }
}