<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Artworks', 'doctrine');

/**
 * BaseArtworks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idartworks
 * @property timestamp $created_at
 * @property integer $fkidartists
 * @property integer $fkidartwork_style
 * @property integer $fkidartwork_type
 * @property Artists $Artists
 * @property ArtworkStyle $ArtworkStyle
 * @property ArtworkType $ArtworkType
 * @property Doctrine_Collection $ArtworksPrices
 * @property Doctrine_Collection $Basket
 * 
 * @method integer             getIdartworks()        Returns the current record's "idartworks" value
 * @method timestamp           getCreatedAt()         Returns the current record's "created_at" value
 * @method integer             getFkidartists()       Returns the current record's "fkidartists" value
 * @method integer             getFkidartworkStyle()  Returns the current record's "fkidartwork_style" value
 * @method integer             getFkidartworkType()   Returns the current record's "fkidartwork_type" value
 * @method Artists             getArtists()           Returns the current record's "Artists" value
 * @method ArtworkStyle        getArtworkStyle()      Returns the current record's "ArtworkStyle" value
 * @method ArtworkType         getArtworkType()       Returns the current record's "ArtworkType" value
 * @method Doctrine_Collection getArtworksPrices()    Returns the current record's "ArtworksPrices" collection
 * @method Doctrine_Collection getBasket()            Returns the current record's "Basket" collection
 * @method Artworks            setIdartworks()        Sets the current record's "idartworks" value
 * @method Artworks            setCreatedAt()         Sets the current record's "created_at" value
 * @method Artworks            setFkidartists()       Sets the current record's "fkidartists" value
 * @method Artworks            setFkidartworkStyle()  Sets the current record's "fkidartwork_style" value
 * @method Artworks            setFkidartworkType()   Sets the current record's "fkidartwork_type" value
 * @method Artworks            setArtists()           Sets the current record's "Artists" value
 * @method Artworks            setArtworkStyle()      Sets the current record's "ArtworkStyle" value
 * @method Artworks            setArtworkType()       Sets the current record's "ArtworkType" value
 * @method Artworks            setArtworksPrices()    Sets the current record's "ArtworksPrices" collection
 * @method Artworks            setBasket()            Sets the current record's "Basket" collection
 * 
 * @package    artworks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtworks extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artworks');
        $this->hasColumn('idartworks', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fkidartists', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fkidartwork_style', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fkidartwork_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Artists', array(
             'local' => 'fkidartists',
             'foreign' => 'idartists'));

        $this->hasOne('ArtworkStyle', array(
             'local' => 'fkidartwork_style',
             'foreign' => 'idartwork_style'));

        $this->hasOne('ArtworkType', array(
             'local' => 'fkidartwork_type',
             'foreign' => 'idartwork_type'));

        $this->hasMany('ArtworksPrices', array(
             'local' => 'idartworks',
             'foreign' => 'fkidartworksfromprices'));

        $this->hasMany('Basket', array(
             'local' => 'idartworks',
             'foreign' => 'fkidartworksfrombasket'));
    }
}