<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AddressType', 'doctrine');

/**
 * BaseAddressType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idaddress_type
 * @property string $label
 * @property Doctrine_Collection $CustomersAddressList
 * 
 * @method integer             getIdaddressType()        Returns the current record's "idaddress_type" value
 * @method string              getLabel()                Returns the current record's "label" value
 * @method Doctrine_Collection getCustomersAddressList() Returns the current record's "CustomersAddressList" collection
 * @method AddressType         setIdaddressType()        Sets the current record's "idaddress_type" value
 * @method AddressType         setLabel()                Sets the current record's "label" value
 * @method AddressType         setCustomersAddressList() Sets the current record's "CustomersAddressList" collection
 * 
 * @package    artworks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAddressType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('address_type');
        $this->hasColumn('idaddress_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('label', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CustomersAddressList', array(
             'local' => 'idaddress_type',
             'foreign' => 'fkidaddress_type'));
    }
}