<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Artists', 'doctrine');

/**
 * BaseArtists
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idartists
 * @property string $name
 * @property Doctrine_Collection $Artworks
 * 
 * @method integer             getIdartists() Returns the current record's "idartists" value
 * @method string              getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getArtworks()  Returns the current record's "Artworks" collection
 * @method Artists             setIdartists() Sets the current record's "idartists" value
 * @method Artists             setName()      Sets the current record's "name" value
 * @method Artists             setArtworks()  Sets the current record's "Artworks" collection
 * 
 * @package    artworks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtists extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artists');
        $this->hasColumn('idartists', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Artworks', array(
             'local' => 'idartists',
             'foreign' => 'fkidartists'));
    }
}