<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ArtworkType', 'doctrine');

/**
 * BaseArtworkType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idartwork_type
 * @property string $label
 * @property Doctrine_Collection $Artworks
 * 
 * @method integer             getIdartworkType()  Returns the current record's "idartwork_type" value
 * @method string              getLabel()          Returns the current record's "label" value
 * @method Doctrine_Collection getArtworks()       Returns the current record's "Artworks" collection
 * @method ArtworkType         setIdartworkType()  Sets the current record's "idartwork_type" value
 * @method ArtworkType         setLabel()          Sets the current record's "label" value
 * @method ArtworkType         setArtworks()       Sets the current record's "Artworks" collection
 * 
 * @package    artworks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtworkType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artwork_type');
        $this->hasColumn('idartwork_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('label', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Artworks', array(
             'local' => 'idartwork_type',
             'foreign' => 'fkidartwork_type'));
    }
}