<?php

/**
 * DialingCodesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DialingCodesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DialingCodesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DialingCodes');
    }
}