# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
  
    enabled_modules:
      - sfGlobalSecureActions
      - sfGlobalBasicActions
      
    # Form security secret (CSRF protection)
    csrf_secret:            72dc073812e5ce12959cf8d0ff29ee6c3c2f5391

    # Localisation & Internationalisation
    charset: utf-8
    default_culture:     fr
    i18n:                true
    
    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    
    standard_helpers: [Partial, Cache, I18N]
       
  .actions:
    login_module: homepage
    login_action: welcome
    
    secure_module: sfGlobalSecureActions
    secure_action: index
    
    error_404_module: errors
    error_404_action: error404
  
