<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/26 20:35:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'phptype' => 'mysqli',
  'dsn' => 'mysql:host=localhost;dbname=artworks',
  'username' => 'artworks',
  'password' => 74108520,
  'encoding' => 'UTF8',
  'name' => 'doctrine',
)),);
