# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing


#Erreurs
errors_show:
  url:   /:sf_culture/error/:numero
  param:  { module: errors, action: Show}
    

# Stepping logics

autoconnect_index:
  url:   /autoconnect/:cryptuid/:hashcode/:crypttimelimit/:forwardurl
  param:  { module: autoconnect, action: index}

stepping_gotostep:
  url:   /:sf_culture/gotostep/
  param:  { module: stepping, action: gotoStep }

stepping_update:    
  url: /:sf_culture/update.:sf_format
  param: { module: stepping, action: update, sf_format: html}
  requirements: { sf_method: put }

stepping_create:  
  url: /:sf_culture/create
  param: { module: stepping, action: create}
  requirements: { sf_method: post }

stepping_form:
  url: /:sf_culture/:action
  param: { module: stepping}
  requirements:    
    sf_culture: (?:fr|en)


# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
