# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing


#Erreurs
errors_show:
  url:   /:sf_culture/error/:numero
  param:  { module: errors, action: Show}
    

# geo logics
geo_geo_search:
  url:   /:sf_culture/geo/geosearch/*
  param:  { module: geo, action: geoSearch }

# Stepping logics

autoconnect_index:
  url:   /autoconnect/:cryptuid/:hashcode/:crypttimelimit/:forwardurl
  param:  { module: autoconnect, action: index}

stepping_gotostep:
  url:   /:sf_culture/gotostep/
  param:  { module: stepping, action: gotoStep }

stepping_update:    
  url: /:sf_culture/update.:sf_format
  param: { module: stepping, action: update, sf_format: html}
  requirements: { sf_method: put }

stepping_create:  
  url: /:sf_culture/create
  param: { module: stepping, action: create}
  requirements: { sf_method: post }

stepping_form:
  url: /:sf_culture/:action
  param: { module: stepping}
  requirements:    
    sf_culture: (?:fr|en)

js_index:
  url:   /:sf_culture/js/generated.:sf_format
  param: { module: js, action: index }  
  requirements:    
    sf_culture: (?:fr|en) 
    sf_method: get
    sf_format: js


# default rules
homepage:
  url:   /fr/
  param: { module: stepping, action: step0 }


