# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false
    csrf_secret:            false 

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            b7a1193ae46caa190b4146b13e254e1f6d50ca73

    enabled_modules:
      - sfGlobalBasicActions
      - sfGlobalGeoActions
      
    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Localisation & Internationalisation
    charset: utf-8
    default_culture:     fr
    i18n:                true

    standard_helpers:       [Partial, I18N]

    # Enable the database manager
    use_database:           true
