# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
# profile routing
# default rules

js_index:
  url:   /:sf_culture/js/generated.:sf_format
  param: { module: js, action: index }  
  requirements:    
    sf_culture: (?:fr|en) 
    sf_method: get
    sf_format: js

myprofile_change_password:
  url:   /:sf_culture/changepassword
  param:  { module: myprofile, action: changePassword }
 
myprofile_change_addresses:
  url:   /:sf_culture/changeaddresses
  param:  { module: myprofile, action: changeAddresses }
  
myprofile_delete_address:
  url:   /:sf_culture/deleteaddress
  param:  { module: myprofile, action: deleteAddress }
  
myprofile_flag_address:
  url:   /:sf_culture/flagaddress
  param:  { module: myprofile, action: flagAddress }

myprofile_add_address:
  url:   /:sf_culture/addaddress
  param:  { module: myprofile, action: addAddress }
  requirements: 
   sf_method: put

myselection_list:
  url:   /:sf_culture/myselection/list
  param:  { module: myselection, action: list }
  
myselection_delete_from_selection:
  url:   /:sf_culture/myselection/delete/:idartworks/:basket_status
  param:  { module: myselection, action: deleteFromMySelection }
  
myprofile_logout:
  url:   /:sf_culture/logout
  param:  { module: myprofile, action: logOut }

myprofile_update:
  url:   /:sf_culture/update 
  param: { module: myprofile, action: update }
  requirements: 
   sf_method: put

homepage:
  url:   /:sf_culture/
  param: { module: myprofile, action: index }


