# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules

js_index:
  url:   /:sf_culture/js/generated.:sf_format
  param: { module: js, action: index }  
  requirements:    
    sf_culture: (?:fr|en) 
    sf_method: get
    sf_format: js


myprofile_change_password:
  url:   /:sf_culture/changepassword
  param:  { module: myprofile, action: changePassword }
 
myprofile_change_addresses:
  url:   /:sf_culture/changeaddresses
  param:  { module: myprofile, action: changeAddresses }

sfGlobalGeoActions_geo:
  url:   /:sf_culture/geosearch
  param:  { module: sfGlobalGeoActions, action: geoSearch }
  
myprofile_logout:
  url:   /:sf_culture/logout
  param:  { module: myprofile, action: logOut }

myprofile_update:
  url:   /:sf_culture/update 
  param: { module: myprofile, action: update }
  requirements: 
   sf_method: put

homepage:
  url:   /:sf_culture/
  param: { module: myprofile, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
