# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:

  .actions:
    login_module: sfGlobalSecureActions
    login_action: index
    
    secure_module: sfGlobalSecureActions
    secure_action: index
    
    error_404_module: errors
    error_404_action: error404
    
  .settings:
 
    enabled_modules:
      - sfGlobalSecureActions
      
    # Form security secret (CSRF protection)
    csrf_secret:            false

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    # Localisation & Internationalisation
    charset: utf-8
    default_culture:     fr
    i18n:                true

    standard_helpers:       [Partial, I18N]